### ISSUE TITLE
Blocks are too close to left-edge in toolbox flyout

### ISSUE THREAD

**Issue by gezakerecsenyi** [codeddraig/ffau#88]
In the toolbox flyout, the blocks are very close to the left edge (to the section selector), and it looks awkward and distracting as it overlaps with the shadow.

This can be fixed by adding:

```css
.blocklyFlyout g.blocklyBlockCanvas {
        transform: translate(10px, 10px)
}
```
